shared:
  image: centos:centos7
  environment:
    RELEASE_FILES: "zstd-cli-linux.tar.gz skopeo-linux.tar.gz"

jobs:
  skopeo:
    requires: [~pr, ~commit]
    environment:
      SKOPEO_PACKAGE: skopeo
    steps:
      - make: |
          yum install -y epel-release
          yum install -y wget git make gcc gcc-c++ jq bzip2
          wget -q -O go1.15.6.tar.gz https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
          tar -C /usr/local -oxzf go1.15.6.tar.gz
          export CURR_DIR=$(pwd)
          mkdir /go && cd /go
          export GOROOT=/usr/local/go && export GOPATH=/go/src && export PATH=${PATH}:${GOROOT}/bin
          git clone https://github.com/containers/${SKOPEO_PACKAGE} $GOPATH/src/github.com/containers/${SKOPEO_PACKAGE}
          cd $GOPATH/src/github.com/containers/${SKOPEO_PACKAGE} && make DISABLE_CGO=1 bin/${SKOPEO_PACKAGE}
          mv bin/${SKOPEO_PACKAGE} $CURR_DIR/ && cd $CURR_DIR/
          chmod +x ${SKOPEO_PACKAGE}
          ./${SKOPEO_PACKAGE} -v
      - test-node12-sha256: |
          DIGEST=$( ./${SKOPEO_PACKAGE} inspect docker://docker.io/node:12 | jq -r '.Digest')
          if [[ -z $DIGEST ]]; then
            echo "unable to get image node:12 sha256 digest"
            exit 1   v
          fi
      - test-alpine-sha256: |
          DIGEST=$( ./${SKOPEO_PACKAGE} inspect docker://docker.io/alpine:latest | jq -r '.Digest')
          if [[ -z $DIGEST ]]; then
            echo "unable to get image alpine:latest sha256 digest"
            exit 1
          fi
      - test-busybox-sha256: |
          DIGEST=$( ./${SKOPEO_PACKAGE} inspect docker://docker.io/busybox:latest | jq -r '.Digest')
          if [[ -z $DIGEST ]]; then
            echo "unable to get image busybox:latest sha256 digest"
            exit 1
          fi
      - package: a=($RELEASE_FILES) && tar -czf ${a[0]} ./${SKOPEO_PACKAGE} && store-cli set ${a[0]} --type=cache --scope=event

  zstd:
    requires: [~pr, ~commit]
    environment:
      ZSTD_PACKAGE: zstd
      ZSTD_VERSION: 1.5.0
    steps:
      - make: |
          yum install -y epel-release
          yum install -y zlib-devel wget make gcc gcc-c++
          wget -q -O zstd-${ZSTD_VERSION}.tar.gz https://github.com/facebook/zstd/releases/download/v${ZSTD_VERSION}/zstd-${ZSTD_VERSION}.tar.gz
          tar -C . -oxzf zstd-${ZSTD_VERSION}.tar.gz
          cd zstd-${ZSTD_VERSION} && make
          chmod +x ./${ZSTD_PACKAGE}
          ./${ZSTD_PACKAGE} --version
      - package: a=($RELEASE_FILES) && tar -czf ${a[1]} ./${ZSTD_PACKAGE} && store-cli set ${a[1]} --type=cache --scope=event

  publish:
    requires: [zstd, skopeo]
    steps:
      - setup-ci: |
          yum install -y epel-release
          yum install -y wget git make gcc gcc-c++ bzip2
          git clone https://github.com/screwdriver-cd/toolbox.git ci
      - tag: ./ci/git-tag.sh
      - publish: ([ ! -z $SD_PULL_REQUEST ] && echo skip publish for PR) || (files=($RELEASE_FILES); for i in "${files[@]}"; do store-cli get $i --type=cache --scope=event; (if [ -f $i ]; then ./ci/git-release.sh; else echo skip $i not found; fi); done)
    secrets:
      # Pushing tags to Git
      - GIT_KEY_BASE64
      # Pushing releases to GitHub
      - GITHUB_TOKEN
